@DevToBeCurious.FollowsCourses.WebApi.UI_HostAddress = https://localhost:7123

GET {{DevToBeCurious.FollowsCourses.WebApi.UI_HostAddress}}/api/Session

###

POST {{DevToBeCurious.FollowsCourses.WebApi.UI_HostAddress}}/api/Session

###
