<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b0456106-5195-44c9-9a79-5c436e4bf4cf</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1-Preview.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0-preview.3.efcore.9.0.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.0.30" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DTBC.FC.Sessions.Infrastructure\DTBC.FC.Sessions.Infrastructure.csproj" />
    <ProjectReference Include="..\DTBC.FC.Sessions.Models\DTBC.FC.Sessions.Models.csproj" />
    <ProjectReference Include="..\Libs\DTBC.FC.Sessions.Application\DTBC.FC.Sessions.Application.csproj" />
    <ProjectReference Include="..\Libs\DTBC.FC.WebApi.Core\DTBC.FC.WebApi.Core.csproj" />
  </ItemGroup>

</Project>
